version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - open-react-hub:/app/.next
    environment:
      - NODE_ENV=development

volumes:
  open-react-hub:


